---
title: "Diabetes Readmission"
author: "Terence Chan"
date: "August 30, 2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, 
                      error = FALSE)
```

```{r}
dat <- read.csv("C:\\Users\\teren\\Desktop\\diabetes_update.csv")
set.seed(1003161366)
```

```{r}
library(car)
readmitted_new <- car::recode(dat$readmitted, "'NO' = 0 ; '<30' = 1 ;'>30' = 1") 
change_new <- car::recode(dat$change, "'No' = 0 ; 'Ch' = 1") 
diabetesMed_new <- car::recode(dat$diabetesMed, "'No' = 0 ; 'Yes' = 1")
gender_new <- car::recode(dat$gender, "'Female' = 1 ; 'Male' = 2")
age_new <- car::recode(dat$age, "'[0-10)' = 5 ; '[10-20)' = 15 ; 
                       '[20-30)' = 25 ; '[30-40)' = 35 ; '[40-50)' = 45 ; 
                       '[50-60)' = 55 ; '[60-70)' = 65 ; '[70-80)' = 75 ;
                       '[80-90)' = 85 ; '[90-100)' = 95") 
race_new <- car::recode(dat$race, "'Caucasian' = 1 ; 'AfricanAmerican' = 2 ;
                        'Asian' = 3 ; 'Hispanic' = 4 ; 'Other' = 5 ; NA = 0")
metformin.rosiglitazone_new <- car::recode(dat$metformin.rosiglitazone, 
                                           "'Steady' = 'Yes'")
metformin_new <- car::recode(dat$metformin, "'Down' = 'Yes' ; 'Up' = 'Yes' ;
                             'Steady' = 'Yes'")
rosiglitazone_new <- car::recode(dat$rosiglitazone, "'Down' = 'Yes' ; 
                                 'Up' = 'Yes' ; 'Steady' = 'Yes'")
insulin_new <- car::recode(dat$insulin, "'Down' = 'Yes' ; 'Up' = 'Yes' ; 
                           'Steady' = 'Yes'")
```

```{r}
library(caret)
library(dplyr)
library(base)
library(DataCombine)
mean(is.na(dat$weight)) 
mean(is.na(dat$payer_code)) 
mean(is.na(dat$medical_specialty)) 
mean(is.na(dat$examide)) 
mean(is.na(dat$citoglipton)) 
dat_new <- subset(dat, select = -c(weight, payer_code)) 
as.data.frame(table(dat_new$metformin.rosiglitazone))
as.data.frame(table(dat_new$metformin))
as.data.frame(table(dat_new$insulin))
as.data.frame(table(dat_new$rosiglitazone))
as.data.frame(table(dat$race))
as.data.frame(table(dat$gender))
as.data.frame(table(dat$medical_specialty))

dat_new <- subset(dat, select = -c(weight, payer_code)) 
dat_new$readmitted = readmitted_new
dat_new$change = change_new  
dat_new$diabetesMed = diabetesMed_new
dat_new$gender = gender_new
dat_new$age = age_new
dat_new$race = race_new
dat_new$metformin.rosiglitazone = metformin.rosiglitazone_new
dat_new$metformin = metformin_new
dat_new$rosiglitazone = rosiglitazone_new
dat_new$insulin = insulin_new

num_medications_new = as.vector(dat_new$num_medications)
dat_new$num_medications = num_medications_new
number_diagnoses_new = as.vector(dat_new$number_diagnoses)
dat_new$number_diagnoses = number_diagnoses_new
Length.of.Stay_new = as.vector(dat_new$Length.of.Stay)
dat_new$Length.of.Stay = Length.of.Stay_new

test.data <- dat_new[sample(seq_len(nrow(dat_new)), size = 20000),]
length(unique(dat_new$patient_nbr))
nrow(dat_new)
length(which(dat_new$patient_nbr %in% test.data$patient_nbr))
train.data <- dat_new[!dat_new$patient_nbr %in% test.data$patient_nbr,]
```

#Models

```{r}
mod1 <- glm(readmitted_new ~ race_new + gender_new + age_new 
            + num_medications_new + number_diagnoses_new + diabetesMed_new 
            + change_new + Length.of.Stay_new + insulin_new,
                 family = "binomial", data = train.data) 
mod1
mod2 <- glm(readmitted_new ~ race_new + gender_new + age_new 
            + num_medications_new + number_diagnoses_new + diabetesMed_new 
            + change_new + Length.of.Stay_new  + metformin_new + insulin_new,
            family = "binomial", data = train.data)
mod2  

mod3 <- glm(readmitted_new ~ race_new + gender_new + age_new 
            + num_medications_new + number_diagnoses_new + diabetesMed_new 
            + change_new + Length.of.Stay_new + metformin_new, 
            family = "binomial", data = train.data) 
mod3
mod4 <- glm(readmitted_new ~ race_new + gender_new + age_new 
            + num_medications_new + number_diagnoses_new + diabetesMed_new 
            + change_new + rosiglitazone_new + Length.of.Stay_new, 
            family = "binomial", data = train.data) 
mod4 
mod5 <- glm(readmitted_new ~ race_new + gender_new + age_new 
            + num_medications_new + number_diagnoses_new + diabetesMed_new 
            + change_new + Length.of.Stay_new + insulin_new + rosiglitazone_new,
            family = "binomial", data = train.data)
mod5

mod6 <- glm(readmitted_new ~ race_new + gender_new + age_new 
            + num_medications_new + number_diagnoses_new + diabetesMed_new 
            + change_new + Length.of.Stay_new , family = "binomial",
            data = train.data)
mod6 
```

#Model Validation (Variable Selection then Model Validation)

```{r}
library(MASS)
stepAIC(mod1, direction = "forward")
```

```{r}
step(mod1, trace = 0, criterion = "BIC", k = log(500))
```

```{r}
library(rms)
library(glmnet)
n <- nrow(train.data)
p1 <- 7 
x1 <- matrix(rnorm(n*p1), nrow = n, ncol = p1)
y1 <- apply(x1[,1:p1], 1, FUN = sum) + rnorm(n)

train_rows <- sample(1:n, (n/101766)*n)
x.train1 <- x1[train_rows, ]
x.test1 <- x1[-train_rows, ]
y.train1 <- y1[train_rows]
y.test1 <- y1[-train_rows]

fit1 <- lrm(readmitted_new ~ race_new + gender_new + age_new + 
    number_diagnoses_new + diabetesMed_new + change_new + Length.of.Stay_new, 
    data = train.data, x = TRUE, y = TRUE, model = TRUE) 

cvfit1 = cv.glmnet(x.train1, y.train1, family = "gaussian")
cvfit1
calib1 <- calibrate(fit1, method = "crossvalidation", B = 10) 
fit1
plot(calib1, main = "Model 1 Cross Validation")
```

```{r}
stepAIC(mod2, direction = "forward")
```

```{r}
step(mod2, trace = 0, criterion = "BIC", k = log(500))
```

```{r}
n <- nrow(train.data)
p2 <- 9 
x2 <- matrix(rnorm(n*p2), nrow = n, ncol = p2)
y2 <- apply(x2[,1:p2], 1, FUN = sum) + rnorm(n)

train_rows <- sample(1:n, (n/101766)*n)
x.train2 <- x2[train_rows, ]
x.test2 <- x2[-train_rows, ]
y.train2 <- y2[train_rows]
y.test2 <- y2[-train_rows]

fit2 <- lrm(readmitted_new ~ race_new + gender_new + age_new + 
    number_diagnoses_new + diabetesMed_new + change_new + Length.of.Stay_new + 
    metformin_new + insulin_new, data = train.data, x = TRUE, y = TRUE, 
    model = TRUE)

cvfit2 = cv.glmnet(x.train2, y.train2, family = "gaussian")
cvfit2
calib2 <- calibrate(fit2, method = "crossvalidation", B = 10) 
fit2
plot(calib2, main = "Model 2 Cross Validation")
```

```{r}
stepAIC(mod3, direction = "forward")
```

```{r}
step(mod3, trace = 0, criterion = "BIC", k = log(500))
```

```{r}
n <- nrow(train.data)
p3 <- 8 
x3 <- matrix(rnorm(n*p3), nrow = n, ncol = p3)
y3 <- apply(x3[,1:p3], 1, FUN = sum) + rnorm(n)

train_rows <- sample(1:n, (n/101766)*n)
x.train3 <- x3[train_rows, ]
x.test3 <- x3[-train_rows, ]
y.train3 <- y3[train_rows]
y.test3 <- y3[-train_rows]

fit3 <- lrm(readmitted_new ~ race_new + gender_new + age_new + 
    number_diagnoses_new + diabetesMed_new + change_new + Length.of.Stay_new + 
    metformin_new, x = TRUE, y = TRUE, model = TRUE) 
cvfit3 = cv.glmnet(x.train3, y.train3, family = "gaussian")
cvfit3
calib3 <- calibrate(fit3, method = "crossvalidation", B = 10) 
fit3
plot(calib3, main = "Model 3 Cross Validation")
```

```{r}
stepAIC(mod4, direction = "forward")
```

```{r}
step(mod4, trace = 0, criterion = "BIC", k = log(500)) 
```

```{r}
n <- nrow(train.data)
p4 <- 7 
x4 <- matrix(rnorm(n*p4), nrow = n, ncol = p4)
y4 <- apply(x4[,1:p4], 1, FUN = sum) + rnorm(n)

train_rows <- sample(1:n, (n/101766)*n)
x.train4 <- x4[train_rows, ]
x.test4 <- x4[-train_rows, ]
y.train4 <- y4[train_rows]
y.test4 <- y4[-train_rows]

fit4 <- lrm(readmitted_new ~ race_new + gender_new + age_new + 
    number_diagnoses_new + diabetesMed_new + change_new + Length.of.Stay_new, 
    x = TRUE, y = TRUE, model = TRUE) 

cvfit4 = cv.glmnet(x.train4, y.train4, family = "gaussian")
cvfit4
calib4 <- calibrate(fit4, method = "crossvalidation", B = 10) 
fit4
plot(calib4, main = "Model 4 Cross Validation")
```

```{r}
stepAIC(mod5, direction = "forward")
```

```{r}
step(mod5, trace = 0, criterion = "BIC", k = log(500))
```

```{r}
n <- nrow(train.data)
p5 <- 7 
x5 <- matrix(rnorm(n*p5), nrow = n, ncol = p5)
y5 <- apply(x5[,1:p5], 1, FUN = sum) + rnorm(n)

train_rows <- sample(1:n, (n/101766)*n)
x.train5 <- x5[train_rows, ]
x.test5 <- x5[-train_rows, ]
y.train5 <- y5[train_rows]
y.test5 <- y5[-train_rows]

fit5 <- lrm(readmitted_new ~ race_new + gender_new + age_new + 
    number_diagnoses_new + diabetesMed_new + change_new + Length.of.Stay_new,
            data = train.data, x = TRUE, y = TRUE, model = TRUE) 

cvfit5 = cv.glmnet(x.train5, y.train5, family = "gaussian")
cvfit5
calib5 <- calibrate(fit5, method = "crossvalidation", B = 10) 
fit5
plot(calib5, main = "Model 5 Cross Validation")
```

```{r}
stepAIC(mod6, direction = "forward")
```

```{r}
step(mod6, trace = 0, criterion = "BIC", k = log(500))
```

```{r}
n <- nrow(train.data)
p6 <- 7 
x6 <- matrix(rnorm(n*p6), nrow = n, ncol = p6)
y6 <- apply(x6[,1:p6], 1, FUN = sum) + rnorm(n)

train_rows <- sample(1:n, (n/101766)*n)
x.train6 <- x6[train_rows, ]
x.test6 <- x6[-train_rows, ]
y.train6 <- y6[train_rows]
y.test6 <- y6[-train_rows]

fit6 <- lrm(readmitted_new ~ race_new + gender_new + age_new + 
    number_diagnoses_new + diabetesMed_new + change_new + Length.of.Stay_new, 
    data = train.data, x = TRUE, y = TRUE, model = TRUE) 

cvfit6 = cv.glmnet(x.train6, y.train6, family = "gaussian")
cvfit6
calib6 <- calibrate(fit6, method = "crossvalidation", B = 10) 
fit6
plot(calib6, main = "Model 6 Cross Validation")
```

#ROC Curves and AUC Values

```{r}
library(pROC)
new_p_mod3 <- predict(fit3, type = "fitted")
new_p1_mod3 <- predict(mod3, type = "response")
new_roc_mod3 <- roc(readmitted_new ~ new_p_mod3)

TPR_mod3 <- new_roc_mod3$sensitivities
FPR_mod3 <- 1 - new_roc_mod3$specificities


{plot(FPR_mod3, TPR_mod3, xlim = c(0,1), ylim = c(0,1), xlab = 'FPR', 
      ylab = 'TPR', type = 'l', lty = 1, lwd = 2, col = 'red', 
      main = "Model 3 ROC Curve")
abline(a=0,b=1, lty = 2, col = 'blue') 
text(0.7,0.4,labels = paste("AUC = ", round(auc(new_roc_mod3), 2)))}
```

```{r}
new_p_mod2 <- predict(fit2, type = "fitted")
new_p1_mod2 <- predict(mod2, type = "response")
new_roc_mod2 <- roc(readmitted_new ~ new_p_mod2)

TPR_mod2 <- new_roc_mod2$sensitivities
FPR_mod2 <- 1 - new_roc_mod2$specificities


{plot(FPR_mod2, TPR_mod2, xlim = c(0,1), ylim = c(0,1), xlab = 'FPR', 
      ylab = 'TPR', type = 'l', lty = 1, lwd = 2, col = 'red', 
      main = "Model 2 ROC Curve")
abline(a=0,b=1, lty = 2, col = 'blue') 
text(0.7,0.4,labels = paste("AUC = ", round(auc(new_roc_mod2), 2)))}
```

# Testing Model 2 and Model 3 against test data

```{r}
pred.prob2 <- predict(fit2, data = train.data, type = "fitted")  
test_pred_prob2 <- predict(mod2, data = test.data, type = "response")
split2 <- quantile(test_pred_prob2, probs = seq(0,1, by = 0.02))
test_split2 <- findInterval(test_pred_prob2, split2, rightmost.closed = TRUE)
pred.prob2 <- tapply(test_pred_prob2, test_split2, mean)
obs.prob2 <- tapply(as.numeric(readmitted_new)-1, test_split2, mean)

{plot(pred.prob2, obs.prob2, type = "l", ylab = "Observed", xlab = "Predicted",
      xlim = c(0,1), ylim = c(0,1), col = "red", main = "Model 2" )
abline(a=0, b=1)}
```

```{r}
pred.prob3 <- predict(fit3, data = train.data, type = "fitted") 
test_pred_prob3 <- predict(mod3, data = test.data, type = "response")
split3 <- quantile(test_pred_prob3, probs = seq(0,1, by = 0.02))
test_split3 <- findInterval(test_pred_prob3, split3, rightmost.closed = TRUE)
pred.prob3 <- tapply(test_pred_prob3, test_split3, mean)
obs.prob3 <- tapply(as.numeric(readmitted_new)-1, test_split3, mean)

{plot(pred.prob3, obs.prob3, type = "l", ylab = "Observed", xlab = "Predicted",
      xlim = c(0,1), ylim = c(0,1), col = "red", main = "Model 3")
abline(a=0, b=1)}
```

#Final Model

```{r}
fit2
new.mod2 <- glm(readmitted_new ~ race_new + gender_new + age_new + 
     number_diagnoses_new + diabetesMed_new + change_new + Length.of.Stay_new + 
     metformin_new + insulin_new,
            family = "binomial", data = train.data)
new.mod2
```





















